# Generated by Django 5.1.6 on 2025-04-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_blockdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='publishDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='publishTIme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
