# Generated by Django 5.1.6 on 2025-04-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_publishtime_questionpaper_publishtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='PublishDateTime',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='publishstatus',
            field=models.CharField(default='unpublished', max_length=10),
        ),
    ]
